### ISSUE TITLE
building with docker build results in error

### ISSUE THREAD

**Issue by lucamaf** [3scale/echo-api#87]
```
Installing nokogiri 1.10.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/opt/echo-api/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.10.2/ext/nokogiri
/opt/rh/rh-ruby23/root/usr/bin/ruby -r ./siteconf20190404-12-zhj5ej.rb
extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.4.0
checking for gzdopen() in -lz... yes
checking for iconv... yes
************************************************************************
IMPORTANT NOTICE:

Building Nokogiri with a packaged version of libxml2-2.9.9
with the following patches applied:
	- 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
	- 0002-Remove-script-macro-support.patch
	- 0003-Update-entities-to-remove-handling-of-ssi.patch

Team Nokogiri will keep on doing their best to provide security
updates in a timely manner, but if this is a concern for you and want
to use the system library instead; abort this installation process and
reinstall nokogiri as follows:

    gem install nokogiri -- --use-system-libraries
        [--with-xml2-config=/path/to/xml2-config]
        [--with-xslt-config=/path/to/xslt-config]

If you are using Bundler, tell it to use the option:

    bundle config build.nokogiri --use-system-libraries
    bundle install

Note, however, that nokogiri is not fully compatible with arbitrary
versions of libxml2 provided by OS/package vendors.
************************************************************************
Extracting libxml2-2.9.9.tar.gz into
tmp/x86_64-redhat-linux-gnu/ports/libxml2/2.9.9... OK
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/rh/rh-ruby23/root/usr/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib64
	--enable-cross-build
	--disable-cross-build
/opt/echo-api/vendor/bundle/ruby/2.3.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:84:in
`apply_patch': Failed to complete patch task; patch(1) or git(1) is required.
(RuntimeError)
from
/opt/echo-api/vendor/bundle/ruby/2.3.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:92:in
`block in patch'
from
/opt/echo-api/vendor/bundle/ruby/2.3.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:90:in
`each'
from
/opt/echo-api/vendor/bundle/ruby/2.3.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:90:in
`patch'
from
/opt/echo-api/vendor/bundle/ruby/2.3.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:152:in
`cook'
	from extconf.rb:365:in `block (2 levels) in process_recipe'
	from extconf.rb:257:in `block in chdir_for_build'
	from extconf.rb:256:in `chdir'
	from extconf.rb:256:in `chdir_for_build'
	from extconf.rb:364:in `block in process_recipe'
	from extconf.rb:262:in `tap'
	from extconf.rb:262:in `process_recipe'
	from extconf.rb:557:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/opt/echo-api/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.10.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/opt/echo-api/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.10.2 for inspection.
Results logged to
/opt/echo-api/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.10.2/gem_make.out

An error occurred while installing nokogiri (1.10.2), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.10.2' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  nokogiri
The command '/bin/sh -c source /opt/echo-api/etc/scl_enable   && bundle install --deployment' returned a non-zero code: 5

```

**Comment by unleashed** [comment]
Sorry @lucamaf - hopefully someone can take over maintenance, I plan to at least do enough to be able to rebuild this with security fixes.
